additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: {{ ocp_domain }}
compute:
- architecture: {{ ocp_arch }}
  hyperthreading: Enabled
  name: worker
  replicas: 2 # {{ ocp_worker_count }}
controlPlane:
  architecture: {{ ocp_arch }}
  hyperthreading: Enabled
  name: master
  replicas: {{ ocp_master_count }}
metadata:
  creationTimestamp: null
  name: {{ ocp_cluster_name }}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{{ pullsecret | regex_replace('\'', '"') }}'
sshKey: |
  {{ ssh_pubkey | regex_replace('"', '') }}